create schema if not exists telemetry_private;

revoke all on schema telemetry_private from public;
grant usage on schema telemetry_private to anon, authenticated, service_role;

create table if not exists telemetry_private.public_growth_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('landing_view', 'signup_started')),
  visitor_key_hash text not null check (visitor_key_hash ~ '^[0-9a-f]{64}$'),
  touch_hash text not null check (touch_hash ~ '^[0-9a-f]{64}$'),
  landing_path text not null check (
    char_length(landing_path) between 1 and 500
    and left(landing_path, 1) = '/'
    and position('?' in landing_path) = 0
    and position('#' in landing_path) = 0
  ),
  source text,
  medium text,
  campaign text,
  term text,
  content text,
  event_day date not null default current_date,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (source is null or char_length(source) between 1 and 100),
  check (medium is null or char_length(medium) between 1 and 100),
  check (campaign is null or char_length(campaign) between 1 and 160),
  check (term is null or char_length(term) between 1 and 160),
  check (content is null or char_length(content) between 1 and 160)
);

create unique index if not exists public_growth_events_dedupe_uidx
  on telemetry_private.public_growth_events(
    event_name,
    visitor_key_hash,
    landing_path,
    touch_hash,
    event_day
  );

create index if not exists public_growth_events_name_occurred_idx
  on telemetry_private.public_growth_events(event_name, occurred_at desc);

create index if not exists public_growth_events_campaign_occurred_idx
  on telemetry_private.public_growth_events(source, medium, campaign, occurred_at desc)
  where source is not null or medium is not null or campaign is not null;

revoke all on telemetry_private.public_growth_events from public, anon, authenticated;
revoke all on telemetry_private.public_growth_events from service_role;
grant select on telemetry_private.public_growth_events to service_role;

create or replace function telemetry_private.capture_public_growth_event_authority(
  p_event_name text,
  p_visitor_key text,
  p_landing_path text,
  p_source text default null,
  p_medium text default null,
  p_campaign text default null,
  p_term text default null,
  p_content text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_name text := lower(btrim(coalesce(p_event_name, '')));
  v_visitor_key text := btrim(coalesce(p_visitor_key, ''));
  v_landing_path text := btrim(coalesce(p_landing_path, ''));
  v_source text := nullif(left(btrim(coalesce(p_source, '')), 100), '');
  v_medium text := nullif(left(btrim(coalesce(p_medium, '')), 100), '');
  v_campaign text := nullif(left(btrim(coalesce(p_campaign, '')), 160), '');
  v_term text := nullif(left(btrim(coalesce(p_term, '')), 160), '');
  v_content text := nullif(left(btrim(coalesce(p_content, '')), 160), '');
  v_visitor_hash text;
  v_touch_hash text;
  v_inserted_id bigint;
begin
  if v_event_name not in ('landing_view', 'signup_started') then
    raise exception using errcode = '22023', message = 'PUBLIC_GROWTH_EVENT_NOT_ALLOWED';
  end if;

  if char_length(v_visitor_key) < 24
    or char_length(v_visitor_key) > 128
    or v_visitor_key !~ '^[A-Za-z0-9_-]+$'
  then
    raise exception using errcode = '22023', message = 'INVALID_PUBLIC_VISITOR_KEY';
  end if;

  if char_length(v_landing_path) < 1
    or char_length(v_landing_path) > 500
    or left(v_landing_path, 1) <> '/'
    or position('?' in v_landing_path) > 0
    or position('#' in v_landing_path) > 0
  then
    raise exception using errcode = '22023', message = 'INVALID_PUBLIC_LANDING_PATH';
  end if;

  v_visitor_hash := encode(
    extensions.digest(v_visitor_key, 'sha256'),
    'hex'
  );
  v_touch_hash := encode(
    extensions.digest(
      concat_ws('|',
        coalesce(v_source, ''),
        coalesce(v_medium, ''),
        coalesce(v_campaign, ''),
        coalesce(v_term, ''),
        coalesce(v_content, '')
      ),
      'sha256'
    ),
    'hex'
  );

  insert into telemetry_private.public_growth_events (
    event_name,
    visitor_key_hash,
    touch_hash,
    landing_path,
    source,
    medium,
    campaign,
    term,
    content
  )
  values (
    v_event_name,
    v_visitor_hash,
    v_touch_hash,
    v_landing_path,
    v_source,
    v_medium,
    v_campaign,
    v_term,
    v_content
  )
  on conflict (event_name, visitor_key_hash, landing_path, touch_hash, event_day)
  do nothing
  returning id into v_inserted_id;

  return jsonb_build_object(
    'accepted', true,
    'event_name', v_event_name,
    'deduplicated', v_inserted_id is null,
    'capture_scope', 'PUBLIC_FUNNEL_V1',
    'raw_visitor_key_stored', false,
    'arbitrary_query_payload_stored', false
  );
end;
$$;

revoke execute on function telemetry_private.capture_public_growth_event_authority(text,text,text,text,text,text,text,text)
from public, service_role;
grant execute on function telemetry_private.capture_public_growth_event_authority(text,text,text,text,text,text,text,text)
to anon, authenticated;

create or replace function public.capture_public_growth_event(
  p_event_name text,
  p_visitor_key text,
  p_landing_path text,
  p_source text default null,
  p_medium text default null,
  p_campaign text default null,
  p_term text default null,
  p_content text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if lower(btrim(coalesce(p_event_name, ''))) not in ('landing_view', 'signup_started') then
    raise exception using errcode = '22023', message = 'PUBLIC_GROWTH_EVENT_NOT_ALLOWED';
  end if;

  if char_length(btrim(coalesce(p_visitor_key, ''))) < 24
    or char_length(btrim(coalesce(p_visitor_key, ''))) > 128
  then
    raise exception using errcode = '22023', message = 'INVALID_PUBLIC_VISITOR_KEY';
  end if;

  if char_length(btrim(coalesce(p_landing_path, ''))) < 1
    or char_length(btrim(coalesce(p_landing_path, ''))) > 500
    or left(btrim(coalesce(p_landing_path, '')), 1) <> '/'
    or position('?' in btrim(coalesce(p_landing_path, ''))) > 0
    or position('#' in btrim(coalesce(p_landing_path, ''))) > 0
  then
    raise exception using errcode = '22023', message = 'INVALID_PUBLIC_LANDING_PATH';
  end if;

  return telemetry_private.capture_public_growth_event_authority(
    p_event_name,
    p_visitor_key,
    p_landing_path,
    p_source,
    p_medium,
    p_campaign,
    p_term,
    p_content
  );
end;
$$;

revoke execute on function public.capture_public_growth_event(text,text,text,text,text,text,text,text)
from public, service_role;
grant execute on function public.capture_public_growth_event(text,text,text,text,text,text,text,text)
to anon, authenticated;

alter table private.growth_event_catalog
  drop constraint if exists growth_event_catalog_capture_authority_check;

alter table private.growth_event_catalog
  add constraint growth_event_catalog_capture_authority_check
  check (capture_authority in ('server_trigger', 'public_capture', 'future_public_capture', 'provider_authority'));

update private.growth_event_catalog
set
  capture_authority = 'public_capture',
  capture_status = 'active',
  updated_at = now()
where event_name in ('landing_view', 'signup_started');

create or replace function private.get_growth_funnel_snapshot_authority(
  p_organization_id uuid,
  p_days integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_since timestamptz;
  v_signup_at timestamptz;
  v_profile_at timestamptz;
  v_student_at timestamptz;
  v_training_at timestamptz;
  v_delivery_at timestamptz;
  v_checkout_at timestamptz;
  v_paid_at timestamptz;
  v_trial_at timestamptz;
  v_workout_count integer;
  v_delivery_count integer;
  v_weekly_coaches integer;
  v_ttfv bigint;
  v_attribution private.growth_attribution%rowtype;
  v_pending_public jsonb;
begin
  if auth.uid() is null then
    raise exception using errcode = '42501', message = 'AUTH_REQUIRED';
  end if;
  if p_organization_id is null or not private.is_org_member(p_organization_id) then
    raise exception using errcode = '42501', message = 'ORG_MEMBER_REQUIRED';
  end if;
  if p_days is null or p_days < 1 or p_days > 365 then
    raise exception using errcode = '22023', message = 'INVALID_GROWTH_WINDOW';
  end if;

  v_since := now() - make_interval(days => p_days);

  select min(e.occurred_at)
  into v_signup_at
  from private.growth_events e
  where e.event_name = 'signup_completed'
    and e.occurred_at >= v_since
    and (
      e.organization_id = p_organization_id
      or exists (
        select 1
        from public.organization_members m
        where m.organization_id = p_organization_id
          and m.user_id = e.actor_user_id
      )
    );

  select
    min(e.occurred_at) filter (where e.event_name = 'coach_profile_completed'),
    min(e.occurred_at) filter (where e.event_name = 'student_created'),
    min(e.occurred_at) filter (where e.event_name = 'training_created_or_duplicated'),
    min(e.occurred_at) filter (where e.event_name = 'training_delivered'),
    min(e.occurred_at) filter (where e.event_name = 'trial_started'),
    min(e.occurred_at) filter (where e.event_name = 'checkout_started'),
    min(e.occurred_at) filter (where e.event_name = 'paid'),
    count(*) filter (where e.event_name = 'workout_logged')::int,
    count(*) filter (where e.event_name = 'training_delivered')::int
  into
    v_profile_at,
    v_student_at,
    v_training_at,
    v_delivery_at,
    v_trial_at,
    v_checkout_at,
    v_paid_at,
    v_workout_count,
    v_delivery_count
  from private.growth_events e
  where e.organization_id = p_organization_id
    and e.occurred_at >= v_since;

  select count(distinct e.actor_user_id)::int
  into v_weekly_coaches
  from private.growth_events e
  where e.organization_id = p_organization_id
    and e.event_name = 'training_delivered'
    and e.occurred_at >= now() - interval '7 days'
    and e.actor_user_id is not null;

  if v_signup_at is not null
    and v_delivery_at is not null
    and v_delivery_at >= v_signup_at
  then
    v_ttfv := extract(epoch from (v_delivery_at - v_signup_at))::bigint;
  end if;

  select *
  into v_attribution
  from private.growth_attribution a
  where a.organization_id = p_organization_id;

  select coalesce(jsonb_agg(c.event_name order by c.event_name), '[]'::jsonb)
  into v_pending_public
  from private.growth_event_catalog c
  where c.capture_status = 'pending';

  return jsonb_build_object(
    'organization_id', p_organization_id,
    'window_days', p_days,
    'funnel', jsonb_build_object(
      'signup_completed_at', v_signup_at,
      'coach_profile_completed_at', v_profile_at,
      'student_created_at', v_student_at,
      'training_created_or_duplicated_at', v_training_at,
      'training_delivered_at', v_delivery_at,
      'trial_started_at', v_trial_at,
      'checkout_started_at', v_checkout_at,
      'paid_at', v_paid_at,
      'time_to_first_value_seconds', v_ttfv
    ),
    'usage', jsonb_build_object(
      'training_deliveries', v_delivery_count,
      'workouts_logged', v_workout_count
    ),
    'north_star', jsonb_build_object(
      'definition', 'coaches_with_at_least_one_training_delivery_in_last_7_days',
      'weekly_value_coaches', v_weekly_coaches,
      'organization_has_weekly_value', v_weekly_coaches > 0
    ),
    'attribution', case
      when v_attribution.organization_id is null then null
      else jsonb_build_object(
        'first_source', v_attribution.first_source,
        'first_medium', v_attribution.first_medium,
        'first_campaign', v_attribution.first_campaign,
        'last_source', v_attribution.last_source,
        'last_medium', v_attribution.last_medium,
        'last_campaign', v_attribution.last_campaign
      )
    end,
    'instrumentation', jsonb_build_object(
      'server_authoritative_capture', true,
      'pending_public_capture_events', v_pending_public,
      'return_d7_measurement', 'PENDING_SESSION_ACTIVITY_EVENT',
      'tracking_core_gate', case
        when jsonb_array_length(v_pending_public) = 0 then 'READY'
        else 'BLOCKED_TRACKING_INCOMPLETE'
      end,
      'ads_release_gate', 'BLOCKED_BY_SEPARATE_RELEASE_GATES',
      'sensitive_health_payload_in_growth_events', false
    ),
    'generated_at', now()
  );
end;
$$;

revoke execute on function private.get_growth_funnel_snapshot_authority(uuid,integer)
from public, anon, service_role;
grant execute on function private.get_growth_funnel_snapshot_authority(uuid,integer)
to authenticated;
