-- Stage 21: harden anonymous student possession-token access with bounded lifetime,
-- server-side rate buckets, idempotent command receipts, security telemetry and v2 RPCs.

alter table public.student_access_links
  add column if not exists revoked_at timestamptz,
  add column if not exists revocation_reason text,
  add column if not exists rotated_from_link_id uuid references public.student_access_links(id) on delete set null,
  add column if not exists rotation_number integer not null default 1;

alter table public.student_access_links
  drop constraint if exists student_access_links_revocation_reason_len_chk;
alter table public.student_access_links
  add constraint student_access_links_revocation_reason_len_chk
  check (revocation_reason is null or char_length(revocation_reason) <= 80);

alter table public.student_access_links
  drop constraint if exists student_access_links_rotation_number_chk;
alter table public.student_access_links
  add constraint student_access_links_rotation_number_chk
  check (rotation_number >= 1);

-- Existing bearer links must not remain immortal. Give currently active legacy links a
-- bounded migration window without exposing or rotating their raw token.
update public.student_access_links
   set expires_at = now() + interval '30 days'
 where is_active
   and expires_at is null;

update public.student_access_links
   set revoked_at = coalesce(revoked_at, updated_at, now()),
       revocation_reason = coalesce(revocation_reason, 'superseded_or_disabled')
 where not is_active
   and revoked_at is null;

create table if not exists private.student_access_rate_buckets (
  link_id uuid not null references public.student_access_links(id) on delete cascade,
  operation text not null check (operation in (
    'get_workout',
    'start_workout',
    'set_completion',
    'get_feedback_context',
    'submit_feedback'
  )),
  window_started_at timestamptz not null,
  request_count integer not null default 1 check (request_count >= 1),
  last_seen_at timestamptz not null default now(),
  primary key (link_id, operation, window_started_at)
);

create index if not exists student_access_rate_buckets_last_seen_idx
  on private.student_access_rate_buckets(last_seen_at);

create table if not exists private.student_access_command_receipts (
  link_id uuid not null references public.student_access_links(id) on delete cascade,
  operation text not null check (operation in ('start_workout','set_completion','submit_feedback')),
  command_id text not null check (command_id ~ '^[0-9a-f]{32}$'),
  response jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key (link_id, operation, command_id)
);

create index if not exists student_access_command_receipts_created_idx
  on private.student_access_command_receipts(created_at);

create table if not exists private.student_access_security_events (
  id bigint generated by default as identity primary key,
  link_id uuid references public.student_access_links(id) on delete set null,
  organization_id uuid,
  student_id uuid,
  operation text not null,
  outcome text not null check (outcome in ('allowed','rate_limited','replay','rotated')),
  command_id text,
  request_count integer,
  occurred_at timestamptz not null default now(),
  check (command_id is null or command_id ~ '^[0-9a-f]{32}$')
);

create index if not exists student_access_security_events_occurred_idx
  on private.student_access_security_events(occurred_at desc);
create index if not exists student_access_security_events_link_idx
  on private.student_access_security_events(link_id, occurred_at desc);

revoke all on private.student_access_rate_buckets from public, anon, authenticated;
revoke all on private.student_access_command_receipts from public, anon, authenticated;
revoke all on private.student_access_security_events from public, anon, authenticated;
grant select on private.student_access_security_events to service_role;

create or replace function private.student_access_context_v2(
  p_token text,
  p_operation text,
  p_limit_per_minute integer
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_access record;
  v_window timestamptz := date_trunc('minute', now());
  v_count integer := 0;
begin
  if p_operation not in (
    'get_workout','start_workout','set_completion','get_feedback_context','submit_feedback'
  ) then
    return jsonb_build_object('ok', false, 'error', 'STUDENT_ACCESS_OPERATION_INVALID');
  end if;

  if p_limit_per_minute is null or p_limit_per_minute < 1 or p_limit_per_minute > 300 then
    return jsonb_build_object('ok', false, 'error', 'STUDENT_ACCESS_LIMIT_INVALID');
  end if;

  if p_token is null or p_token !~ '^[0-9a-fA-F]{64}$' then
    return jsonb_build_object('ok', false, 'error', 'STUDENT_ACCESS_INVALID');
  end if;

  select * into v_access from private.resolve_student_access(p_token);
  if not found then
    return jsonb_build_object('ok', false, 'error', 'STUDENT_ACCESS_INVALID');
  end if;

  delete from private.student_access_rate_buckets
   where link_id = v_access.link_id
     and window_started_at < now() - interval '2 days';

  insert into private.student_access_rate_buckets as b (
    link_id, operation, window_started_at, request_count, last_seen_at
  ) values (
    v_access.link_id, p_operation, v_window, 1, now()
  )
  on conflict (link_id, operation, window_started_at)
  do update set
    request_count = b.request_count + 1,
    last_seen_at = now()
  returning request_count into v_count;

  if v_count > p_limit_per_minute then
    insert into private.student_access_security_events (
      link_id, organization_id, student_id, operation, outcome, request_count
    ) values (
      v_access.link_id,
      v_access.organization_id,
      v_access.student_id,
      p_operation,
      'rate_limited',
      v_count
    );

    return jsonb_build_object(
      'ok', false,
      'error', 'STUDENT_ACCESS_RATE_LIMITED',
      'retry_after_seconds', greatest(1, 60 - extract(second from now())::int)
    );
  end if;

  update public.student_access_links
     set last_used_at = now()
   where id = v_access.link_id;

  return jsonb_build_object(
    'ok', true,
    'link_id', v_access.link_id,
    'organization_id', v_access.organization_id,
    'student_id', v_access.student_id,
    'request_count', v_count
  );
end;
$$;

revoke all on function private.student_access_context_v2(text,text,integer) from public, anon, authenticated;

create or replace function private.student_access_command_begin_v2(
  p_link_id uuid,
  p_operation text,
  p_command_id text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_inserted integer := 0;
  v_response jsonb;
begin
  if p_operation not in ('start_workout','set_completion','submit_feedback') then
    return jsonb_build_object('mode', 'blocked', 'response', jsonb_build_object('error','STUDENT_COMMAND_OPERATION_INVALID'));
  end if;

  if p_command_id is null or p_command_id !~ '^[0-9a-f]{32}$' then
    return jsonb_build_object('mode', 'blocked', 'response', jsonb_build_object('error','STUDENT_COMMAND_ID_INVALID'));
  end if;

  delete from private.student_access_command_receipts
   where link_id = p_link_id
     and created_at < now() - interval '30 days';

  insert into private.student_access_command_receipts (
    link_id, operation, command_id
  ) values (
    p_link_id, p_operation, p_command_id
  )
  on conflict do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted = 1 then
    return jsonb_build_object('mode', 'new');
  end if;

  select r.response into v_response
    from private.student_access_command_receipts r
   where r.link_id = p_link_id
     and r.operation = p_operation
     and r.command_id = p_command_id;

  if v_response is null then
    return jsonb_build_object(
      'mode', 'blocked',
      'response', jsonb_build_object('error','STUDENT_COMMAND_IN_PROGRESS')
    );
  end if;

  insert into private.student_access_security_events (
    link_id, organization_id, student_id, operation, outcome, command_id
  )
  select l.id, l.organization_id, l.student_id, p_operation, 'replay', p_command_id
    from public.student_access_links l
   where l.id = p_link_id;

  return jsonb_build_object('mode', 'replay', 'response', v_response);
end;
$$;

revoke all on function private.student_access_command_begin_v2(uuid,text,text) from public, anon, authenticated;

create or replace function private.student_access_command_finish_v2(
  p_link_id uuid,
  p_operation text,
  p_command_id text,
  p_response jsonb
)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  update private.student_access_command_receipts
     set response = p_response,
         completed_at = now()
   where link_id = p_link_id
     and operation = p_operation
     and command_id = p_command_id;

  if not found then
    raise exception using errcode = 'P0001', message = 'STUDENT_COMMAND_RECEIPT_MISSING';
  end if;

  insert into private.student_access_security_events (
    link_id, organization_id, student_id, operation, outcome, command_id
  )
  select l.id, l.organization_id, l.student_id, p_operation, 'allowed', p_command_id
    from public.student_access_links l
   where l.id = p_link_id;
end;
$$;

revoke all on function private.student_access_command_finish_v2(uuid,text,text,jsonb) from public, anon, authenticated;

create or replace function public.issue_student_access_token_v2(p_student_id uuid)
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_previous_id uuid;
  v_previous_rotation integer := 0;
  v_token text;
  v_new_id uuid;
begin
  select l.id, l.rotation_number
    into v_previous_id, v_previous_rotation
    from public.student_access_links l
   where l.student_id = p_student_id
     and l.is_active
   order by l.created_at desc
   limit 1;

  if v_previous_id is not null and exists (
    select 1
      from public.student_access_links l
     where l.id = v_previous_id
       and l.created_at > now() - interval '30 seconds'
  ) then
    raise exception using errcode = 'P0001', message = 'STUDENT_ACCESS_ROTATION_COOLDOWN';
  end if;

  v_token := public.issue_student_access_token(p_student_id);

  select l.id into v_new_id
    from public.student_access_links l
   where l.token_hash = extensions.digest(v_token, 'sha256')
   limit 1;

  if v_new_id is null then
    raise exception using errcode = 'P0001', message = 'STUDENT_ACCESS_ROTATION_RESULT_MISSING';
  end if;

  update public.student_access_links
     set expires_at = now() + interval '30 days',
         rotated_from_link_id = v_previous_id,
         rotation_number = greatest(1, coalesce(v_previous_rotation, 0) + 1)
   where id = v_new_id;

  if v_previous_id is not null then
    update public.student_access_links
       set revoked_at = coalesce(revoked_at, now()),
           revocation_reason = coalesce(revocation_reason, 'rotated')
     where id = v_previous_id;
  end if;

  insert into private.student_access_security_events (
    link_id, organization_id, student_id, operation, outcome
  )
  select l.id, l.organization_id, l.student_id, 'issue_token', 'rotated'
    from public.student_access_links l
   where l.id = v_new_id;

  return v_token;
end;
$$;

revoke all on function public.issue_student_access_token_v2(uuid) from public, anon;
grant execute on function public.issue_student_access_token_v2(uuid) to authenticated;

create or replace function public.get_student_workout_v2(p_token text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_context jsonb;
begin
  v_context := private.student_access_context_v2(p_token, 'get_workout', 90);
  if coalesce((v_context ->> 'ok')::boolean, false) is false then
    return v_context;
  end if;
  return public.get_student_workout(p_token);
end;
$$;

revoke all on function public.get_student_workout_v2(text) from public;
grant execute on function public.get_student_workout_v2(text) to anon, authenticated;

create or replace function public.get_student_feedback_context_v2(p_token text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_context jsonb;
begin
  v_context := private.student_access_context_v2(p_token, 'get_feedback_context', 45);
  if coalesce((v_context ->> 'ok')::boolean, false) is false then
    return v_context;
  end if;
  return public.get_student_feedback_context(p_token);
end;
$$;

revoke all on function public.get_student_feedback_context_v2(text) from public;
grant execute on function public.get_student_feedback_context_v2(text) to anon, authenticated;

create or replace function public.start_student_workout_v2(
  p_token text,
  p_command_id text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_context jsonb;
  v_begin jsonb;
  v_link_id uuid;
  v_session_id uuid;
  v_response jsonb;
begin
  v_context := private.student_access_context_v2(p_token, 'start_workout', 12);
  if coalesce((v_context ->> 'ok')::boolean, false) is false then
    return v_context;
  end if;

  v_link_id := (v_context ->> 'link_id')::uuid;
  v_begin := private.student_access_command_begin_v2(v_link_id, 'start_workout', p_command_id);
  if v_begin ->> 'mode' <> 'new' then
    return v_begin -> 'response';
  end if;

  v_session_id := public.start_student_workout(p_token);
  v_response := jsonb_build_object('session_id', v_session_id, 'replayed', false);
  perform private.student_access_command_finish_v2(v_link_id, 'start_workout', p_command_id, v_response);
  return v_response;
end;
$$;

revoke all on function public.start_student_workout_v2(text,text) from public;
grant execute on function public.start_student_workout_v2(text,text) to anon, authenticated;

create or replace function public.set_student_exercise_completion_v2(
  p_token text,
  p_session_id uuid,
  p_exercise_id uuid,
  p_completed boolean,
  p_command_id text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_context jsonb;
  v_begin jsonb;
  v_link_id uuid;
  v_response jsonb;
begin
  v_context := private.student_access_context_v2(p_token, 'set_completion', 60);
  if coalesce((v_context ->> 'ok')::boolean, false) is false then
    return v_context;
  end if;

  v_link_id := (v_context ->> 'link_id')::uuid;
  v_begin := private.student_access_command_begin_v2(v_link_id, 'set_completion', p_command_id);
  if v_begin ->> 'mode' <> 'new' then
    return v_begin -> 'response';
  end if;

  v_response := public.set_student_exercise_completion(
    p_token, p_session_id, p_exercise_id, p_completed
  );
  perform private.student_access_command_finish_v2(v_link_id, 'set_completion', p_command_id, v_response);
  return v_response;
end;
$$;

revoke all on function public.set_student_exercise_completion_v2(text,uuid,uuid,boolean,text) from public;
grant execute on function public.set_student_exercise_completion_v2(text,uuid,uuid,boolean,text) to anon, authenticated;

create or replace function public.submit_student_workout_feedback_v2(
  p_token text,
  p_session_id uuid,
  p_perceived_exertion integer,
  p_pain_score integer,
  p_energy_score integer,
  p_pain_location text,
  p_note text,
  p_command_id text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_context jsonb;
  v_begin jsonb;
  v_link_id uuid;
  v_response jsonb;
begin
  v_context := private.student_access_context_v2(p_token, 'submit_feedback', 12);
  if coalesce((v_context ->> 'ok')::boolean, false) is false then
    return v_context;
  end if;

  v_link_id := (v_context ->> 'link_id')::uuid;
  v_begin := private.student_access_command_begin_v2(v_link_id, 'submit_feedback', p_command_id);
  if v_begin ->> 'mode' <> 'new' then
    return v_begin -> 'response';
  end if;

  v_response := public.submit_student_workout_feedback(
    p_token,
    p_session_id,
    p_perceived_exertion,
    p_pain_score,
    p_energy_score,
    p_pain_location,
    p_note
  );
  perform private.student_access_command_finish_v2(v_link_id, 'submit_feedback', p_command_id, v_response);
  return v_response;
end;
$$;

revoke all on function public.submit_student_workout_feedback_v2(text,uuid,integer,integer,integer,text,text,text) from public;
grant execute on function public.submit_student_workout_feedback_v2(text,uuid,integer,integer,integer,text,text,text) to anon, authenticated;

-- Legacy possession-token RPCs are no longer client-callable after v2 exists.
-- The v2 security-definer boundary may still invoke them internally as owner.
revoke execute on function public.issue_student_access_token(uuid) from authenticated;
revoke execute on function public.get_student_workout(text) from anon, authenticated;
revoke execute on function public.start_student_workout(text) from anon, authenticated;
revoke execute on function public.set_student_exercise_completion(text,uuid,uuid,boolean) from anon, authenticated;
revoke execute on function public.get_student_feedback_context(text) from anon, authenticated;
revoke execute on function public.submit_student_workout_feedback(text,uuid,integer,integer,integer,text,text) from anon, authenticated;

comment on function public.issue_student_access_token_v2(uuid) is
  'Rotates the student bearer token, expires it after 30 days, and never stores the raw token.';
comment on function public.get_student_workout_v2(text) is
  'Rate-bounded student workout read boundary for anonymous possession-token access.';
comment on function public.start_student_workout_v2(text,text) is
  'Rate-bounded and idempotent student workout start boundary using a 128-bit client command id.';
comment on function public.set_student_exercise_completion_v2(text,uuid,uuid,boolean,text) is
  'Rate-bounded and idempotent exercise completion boundary using a 128-bit client command id.';
comment on function public.submit_student_workout_feedback_v2(text,uuid,integer,integer,integer,text,text,text) is
  'Rate-bounded and idempotent student feedback boundary using a 128-bit client command id.';
