create table if not exists private.growth_capture_failures (
  id bigint generated by default as identity primary key,
  event_name text,
  source_entity_table text,
  source_entity_id uuid,
  error_state text not null,
  error_fingerprint text not null,
  occurred_at timestamptz not null default now()
);

create index if not exists growth_capture_failures_occurred_idx
  on private.growth_capture_failures(occurred_at desc);

create index if not exists growth_capture_failures_event_idx
  on private.growth_capture_failures(event_name, occurred_at desc);

revoke all on private.growth_capture_failures from public, anon, authenticated;
revoke all on private.growth_capture_failures from service_role;
grant select on private.growth_capture_failures to service_role;

create or replace function private.append_growth_event(
  p_event_name text,
  p_organization_id uuid,
  p_actor_user_id uuid,
  p_event_source text,
  p_source_entity_table text,
  p_source_entity_id uuid,
  p_occurred_at timestamptz default now()
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_catalog private.growth_event_catalog%rowtype;
  v_state text;
  v_fingerprint text;
begin
  begin
    select * into v_catalog
    from private.growth_event_catalog c
    where c.event_name = p_event_name;

    if v_catalog.event_name is null or v_catalog.capture_status <> 'active' then
      raise exception using errcode = '22023', message = 'GROWTH_EVENT_NOT_ACTIVE';
    end if;
    if p_event_source not in ('server_trigger', 'provider_authority') then
      raise exception using errcode = '22023', message = 'INVALID_GROWTH_EVENT_SOURCE';
    end if;

    insert into private.growth_events (
      event_name,
      organization_id,
      actor_user_id,
      event_source,
      source_entity_table,
      source_entity_id,
      occurred_at
    )
    values (
      p_event_name,
      p_organization_id,
      p_actor_user_id,
      p_event_source,
      p_source_entity_table,
      p_source_entity_id,
      coalesce(p_occurred_at, now())
    )
    on conflict do nothing;
  exception when others then
    v_state := sqlstate;
    v_fingerprint := md5(coalesce(sqlerrm, 'UNKNOWN_GROWTH_CAPTURE_ERROR'));
    begin
      insert into private.growth_capture_failures (
        event_name,
        source_entity_table,
        source_entity_id,
        error_state,
        error_fingerprint
      )
      values (
        left(p_event_name, 80),
        left(p_source_entity_table, 100),
        p_source_entity_id,
        left(coalesce(v_state, 'XXXXX'), 5),
        v_fingerprint
      );
    exception when others then
      null;
    end;
  end;
end;
$$;

revoke execute on function private.append_growth_event(text,uuid,uuid,text,text,uuid,timestamptz)
from public, anon, authenticated, service_role;
