-- Stage 24: derive bounded, privacy-minimized abuse signals from the existing
-- possession-token security event stream without promoting incident-response evidence.
--
-- Failure classes:
--   BGF-STUDENT-ACCESS-ABUSE-BLIND-SPOT-160
--   BGF-STUDENT-ACCESS-ABUSE-THRESHOLD-DRIFT-161
--   BGF-INCIDENT-GATE-SELF-ATTESTATION-162

create table if not exists private.student_access_security_signals (
  id bigint generated by default as identity primary key,
  signal_type text not null check (signal_type in (
    'rate_limit_burst',
    'command_replay_burst',
    'token_rotation_burst'
  )),
  severity text not null check (severity in ('medium','high','critical')),
  subject_key text not null check (char_length(subject_key) between 6 and 96),
  link_id uuid references public.student_access_links(id) on delete set null,
  organization_id uuid,
  student_id uuid,
  operation text not null,
  window_started_at timestamptz not null,
  event_count integer not null check (event_count >= 1),
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (signal_type, subject_key, operation, window_started_at),
  check (last_seen_at >= first_seen_at)
);

create index if not exists student_access_security_signals_last_seen_idx
  on private.student_access_security_signals(last_seen_at desc);
create index if not exists student_access_security_signals_org_last_seen_idx
  on private.student_access_security_signals(organization_id, last_seen_at desc);
create index if not exists student_access_security_signals_link_fk_idx
  on private.student_access_security_signals(link_id);

-- Cover the rolling-window lookups executed by the detector.
create index if not exists student_access_security_events_abuse_window_idx
  on private.student_access_security_events(outcome, link_id, operation, occurred_at desc);
create index if not exists student_access_security_events_rotation_subject_idx
  on private.student_access_security_events(outcome, organization_id, student_id, occurred_at desc);

-- service_role had SELECT on Stage 21 security events but no USAGE on the private
-- schema. Granting schema visibility is required for the security-invoker posture view;
-- object privileges remain explicitly fail-closed.
grant usage on schema private to service_role;
revoke all on private.student_access_security_signals from public, anon, authenticated;
grant select on private.student_access_security_signals to service_role;

create or replace function private.detect_student_access_abuse_signal_v1()
returns trigger
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_count bigint := 0;
  v_first_seen timestamptz;
  v_window_start timestamptz;
  v_signal_type text;
  v_severity text;
  v_subject_key text;
begin
  -- Authority: 10 rate-limited events for the same link+operation in rolling 5m.
  if new.outcome = 'rate_limited' and new.link_id is not null then
    select count(*), min(e.occurred_at)
      into v_count, v_first_seen
      from private.student_access_security_events e
     where e.outcome = 'rate_limited'
       and e.link_id = new.link_id
       and e.operation = new.operation
       and e.occurred_at >= new.occurred_at - interval '5 minutes'
       and e.occurred_at <= new.occurred_at;

    if v_count >= 10 then
      v_signal_type := 'rate_limit_burst';
      v_severity := 'high';
      v_subject_key := 'link:' || new.link_id::text;
      v_window_start := date_bin(
        interval '5 minutes',
        new.occurred_at,
        timestamptz '2000-01-01 00:00:00+00'
      );
    end if;

  -- Authority: 3 replay events for the same link+operation in rolling 10m.
  elsif new.outcome = 'replay' and new.link_id is not null then
    select count(*), min(e.occurred_at)
      into v_count, v_first_seen
      from private.student_access_security_events e
     where e.outcome = 'replay'
       and e.link_id = new.link_id
       and e.operation = new.operation
       and e.occurred_at >= new.occurred_at - interval '10 minutes'
       and e.occurred_at <= new.occurred_at;

    if v_count >= 3 then
      v_signal_type := 'command_replay_burst';
      v_severity := 'high';
      v_subject_key := 'link:' || new.link_id::text;
      v_window_start := date_bin(
        interval '10 minutes',
        new.occurred_at,
        timestamptz '2000-01-01 00:00:00+00'
      );
    end if;

  -- Authority: 4 token rotations for the same organization+student in rolling 30m.
  elsif new.outcome = 'rotated'
    and new.organization_id is not null
    and new.student_id is not null then
    select count(*), min(e.occurred_at)
      into v_count, v_first_seen
      from private.student_access_security_events e
     where e.outcome = 'rotated'
       and e.organization_id = new.organization_id
       and e.student_id = new.student_id
       and e.occurred_at >= new.occurred_at - interval '30 minutes'
       and e.occurred_at <= new.occurred_at;

    if v_count >= 4 then
      v_signal_type := 'token_rotation_burst';
      v_severity := 'medium';
      v_subject_key := 'student:' || new.student_id::text;
      v_window_start := date_bin(
        interval '30 minutes',
        new.occurred_at,
        timestamptz '2000-01-01 00:00:00+00'
      );
    end if;
  end if;

  if v_signal_type is not null then
    insert into private.student_access_security_signals as s (
      signal_type,
      severity,
      subject_key,
      link_id,
      organization_id,
      student_id,
      operation,
      window_started_at,
      event_count,
      first_seen_at,
      last_seen_at
    ) values (
      v_signal_type,
      v_severity,
      v_subject_key,
      new.link_id,
      new.organization_id,
      new.student_id,
      new.operation,
      v_window_start,
      v_count::integer,
      coalesce(v_first_seen, new.occurred_at),
      new.occurred_at
    )
    on conflict (signal_type, subject_key, operation, window_started_at)
    do update set
      severity = excluded.severity,
      link_id = excluded.link_id,
      organization_id = excluded.organization_id,
      student_id = excluded.student_id,
      event_count = greatest(s.event_count, excluded.event_count),
      first_seen_at = least(s.first_seen_at, excluded.first_seen_at),
      last_seen_at = greatest(s.last_seen_at, excluded.last_seen_at),
      updated_at = now();
  end if;

  return new;
end;
$$;

revoke all on function private.detect_student_access_abuse_signal_v1()
  from public, anon, authenticated;

drop trigger if exists student_access_security_abuse_signal_v1
  on private.student_access_security_events;
create trigger student_access_security_abuse_signal_v1
  after insert on private.student_access_security_events
  for each row
  when (new.outcome in ('rate_limited','replay','rotated'))
  execute function private.detect_student_access_abuse_signal_v1();

-- Service-side posture is derived from recent signals. It does not mutate an incident
-- gate, does not acknowledge/resolve incidents and does not constitute a tabletop.
create or replace view private.student_access_security_posture_v1
with (security_invoker = true)
as
select
  now() as evaluated_at,
  case
    when exists (
      select 1
        from private.student_access_security_signals s
       where s.last_seen_at >= now() - interval '60 minutes'
         and s.severity in ('high','critical')
    ) then 'investigate'
    when exists (
      select 1
        from private.student_access_security_signals s
       where s.last_seen_at >= now() - interval '60 minutes'
         and s.severity = 'medium'
    ) then 'observe'
    else 'quiet'
  end as posture,
  (
    select count(*)::integer
      from private.student_access_security_signals s
     where s.last_seen_at >= now() - interval '60 minutes'
  ) as signals_60m,
  (
    select count(*)::integer
      from private.student_access_security_signals s
     where s.signal_type = 'rate_limit_burst'
       and s.last_seen_at >= now() - interval '60 minutes'
  ) as rate_limit_burst_signals_60m,
  (
    select count(*)::integer
      from private.student_access_security_signals s
     where s.signal_type = 'command_replay_burst'
       and s.last_seen_at >= now() - interval '60 minutes'
  ) as command_replay_burst_signals_60m,
  (
    select count(*)::integer
      from private.student_access_security_signals s
     where s.signal_type = 'token_rotation_burst'
       and s.last_seen_at >= now() - interval '60 minutes'
  ) as token_rotation_burst_signals_60m,
  (
    select count(*)::integer
      from private.student_access_security_events e
     where e.occurred_at >= now() - interval '15 minutes'
  ) as security_events_15m,
  (
    select count(*)::integer
      from private.student_access_security_events e
     where e.outcome = 'rate_limited'
       and e.occurred_at >= now() - interval '15 minutes'
  ) as rate_limited_events_15m,
  (
    select count(*)::integer
      from private.student_access_security_events e
     where e.outcome = 'replay'
       and e.occurred_at >= now() - interval '15 minutes'
  ) as replay_events_15m;

revoke all on private.student_access_security_posture_v1 from public, anon, authenticated;
grant select on private.student_access_security_posture_v1 to service_role;

comment on table private.student_access_security_signals is
  'Derived possession-token abuse signals. Operational observability only; not incident-response evidence or launch authority.';
comment on view private.student_access_security_posture_v1 is
  'Derived recent security posture for service-side operations. Does not promote the incident_response gate.';
