name: fitnexus_app
description: "FitNexus Coach BlackGold — Coach Operating System."
publish_to: "none"

version: 0.9.0+3

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.15
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.0.0
  qr_flutter: ^4.1.0
  in_app_purchase: ^3.3.0
  in_app_purchase_android: ^0.5.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/
